<a href="https://colab.research.google.com/github/shubham25091998/machine_learning/blob/main/NumpyOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [8]:
arr1 = np.arange(10)
arr2 = np.arange(10,20)

print(arr1)
print(arr2)

# adding to array
print(arr1 + arr2) # each element is added to its respective index
                   # note : Array size must be same

# arithmatic operations on array
print(arr1 * 10)
print(arr1 + 10)



[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[10 12 14 16 18 20 22 24 26 28]
[ 0 10 20 30 40 50 60 70 80 90]
[10 11 12 13 14 15 16 17 18 19]


In [14]:
# numpy array functions

# square root
print(np.sqrt(arr1))

# square
print(np.square(arr1))

# exponential
print(np.exp(arr1))

# trignometry
print(np.sin(arr1))

# log
print(np.log(arr1)) # natural log

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[ 0  1  4  9 16 25 36 49 64 81]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]
[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458]


<ipython-input-14-2930266342>:16: RuntimeWarning: divide by zero encountered in log
  print(np.log(arr1)) # natural log
