<a href="https://colab.research.google.com/github/shubham25091998/machine_learning/blob/main/NumPyBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
#numpy array
lst = [1,2,3]

one_D_array = np.array(lst)
print(one_D_array)

lst = [[1,2,3],
       [4,5,6],
       [7,8,9]]
two_D_array = np.array(lst)
print(two_D_array)


[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# create numpy array using range
arr1 = np.arange(0,10,2)
print(arr1)

[0 2 4 6 8]


In [7]:
# create array with all 0

# 1D array
arr2 = np.zeros(4)
print(arr2)

# 2D array
arr3 = np.zeros((2,2))
print(arr3)

[0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]]


In [9]:
# create array with all 1

#1D array
arr1 = np.ones(3)
print(arr1)

#2D array
arr2 = np.ones((3,3))
print(arr2)

[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
# creating points equally spaced between given range

arr1 = np.linspace(0,10,20)
print(arr1)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [11]:
# creating identity matrix

matrix = np.eye(4)
print(matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [14]:
# random number array

# random numbers
arr = np.random.rand(5)
print(arr)

# random array which distributed around 0
arr = np.random.randn(5)
print(arr)

[0.30347902 0.7996613  0.2226208  0.53795583 0.78276583]
[ 0.53397914 -1.63406916 -0.12206434 -1.21221813 -0.7745755 ]
