<a href="https://colab.research.google.com/github/shubham25091998/machine_learning/blob/main/NumpyOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [8]:
arr1 = np.arange(10)
arr2 = np.arange(10,20)

print(arr1)
print(arr2)

# adding to array
print(arr1 + arr2) # each element is added to its respective index
                   # note : Array size must be same

# arithmatic operations on array
print(arr1 * 10)
print(arr1 + 10)



[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[10 12 14 16 18 20 22 24 26 28]
[ 0 10 20 30 40 50 60 70 80 90]
[10 11 12 13 14 15 16 17 18 19]


In [14]:
# numpy array functions

# square root
print(np.sqrt(arr1))

# square
print(np.square(arr1))

# exponential
print(np.exp(arr1))

# trignometry
print(np.sin(arr1))

# log
print(np.log(arr1)) # natural log

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[ 0  1  4  9 16 25 36 49 64 81]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]
[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458]


<ipython-input-14-2930266342>:16: RuntimeWarning: divide by zero encountered in log
  print(np.log(arr1)) # natural log


# Exercise

In [15]:
# array of 10 5's
print(np.ones(10) * 5)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [17]:
# array of int from 10 to 50
print(np.arange(10, 50, 1))

# array of all even int from 10 to 50
print(np.arange(10,50,2))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [22]:
# 3x3 matrix for value 0 - 8
print(np.arange(9).reshape(3,3))

# 3x3 identity matrix

print(np.eye(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [32]:
# random number between 0 - 1

print(np.random.rand(1))

# 25 random number of normal distribution
print(np.random.randn(25))

[0.48715876]
[ 0.85072353 -1.4271656   0.80081979 -0.61619443 -0.69232459 -0.43806204
 -1.22298157  0.89082378 -1.09311231  0.16549795 -0.62774479  0.09507649
  0.51987862 -0.10285527 -0.10431349  0.12062326 -2.09761949 -0.41745737
 -0.34669682  0.38141598 -0.1423793   0.1972251   0.06587698  0.09828683
  1.42544651]


In [36]:
print(np.arange(0.01,1.01,0.01).reshape(10,10))

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [37]:
print(np.arange(1,101).reshape(10,10) * 0.01)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [39]:
print(np.linspace(0.01, 1, 100).reshape(10,10))

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [41]:
# array with 20 linearly spaced points between 0 - 1
print(np.linspace(0,1, 20))

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [43]:
mat = np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [44]:
print(mat[2:, 1:])

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [45]:
print(mat[3][4])

20


In [47]:
print(mat[:3,1:2])

[[ 2]
 [ 7]
 [12]]


In [48]:
print(mat[4])

[21 22 23 24 25]


In [49]:
# sum of all value in mat
print(mat.sum())

325


In [51]:
# standard deviation
print(np.std(mat))

# or
print(mat.std())

7.211102550927978
7.211102550927978


In [58]:
# sum of all column elements
print(np.sum(mat, axis = 0))

[55 60 65 70 75]
