<a href="https://colab.research.google.com/github/shubham25091998/machine_learning/blob/main/NumPyBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
#numpy array
lst = [1,2,3]

one_D_array = np.array(lst)
print(one_D_array)

lst = [[1,2,3],
       [4,5,6],
       [7,8,9]]
two_D_array = np.array(lst)
print(two_D_array)


[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
# create numpy array using range
arr1 = np.arange(0,10,2)
print(arr1)

[0 2 4 6 8]


In [5]:
# create array with all 0

# 1D array
arr2 = np.zeros(4)
print(arr2)

# 2D array
arr3 = np.zeros((2,2))
print(arr3)

[0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]]


In [6]:
# create array with all 1

#1D array
arr1 = np.ones(3)
print(arr1)

#2D array
arr2 = np.ones((3,3))
print(arr2)

[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
# creating points equally spaced between given range

arr1 = np.linspace(0,10,20)
print(arr1)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [8]:
# creating identity matrix

matrix = np.eye(4)
print(matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
# random number array

# random numbers
arr = np.random.rand(5)
print(arr)

# random array which distributed around 0
arr = np.random.randn(5)
print(arr)

[0.91471239 0.03661483 0.95517181 0.20438826 0.50859784]
[-0.0277103  -1.41141484 -0.41293778  1.95073128 -0.27713266]


In [13]:
# getting random int -> start, end, count default = 1
print(np.random.randint(0, 10, 20))

[7 0 9 9 9 5 5 7 6 1 4 2 5 0 9 5 6 6 7 3]


In [17]:
# reshaping the existing array
# note no of elements in output array should be same as no of elements in existing array

arr1 = np.arange(0,125,1)

arr2 = arr1.reshape(5,5,5)
print(arr2)

[[[  0   1   2   3   4]
  [  5   6   7   8   9]
  [ 10  11  12  13  14]
  [ 15  16  17  18  19]
  [ 20  21  22  23  24]]

 [[ 25  26  27  28  29]
  [ 30  31  32  33  34]
  [ 35  36  37  38  39]
  [ 40  41  42  43  44]
  [ 45  46  47  48  49]]

 [[ 50  51  52  53  54]
  [ 55  56  57  58  59]
  [ 60  61  62  63  64]
  [ 65  66  67  68  69]
  [ 70  71  72  73  74]]

 [[ 75  76  77  78  79]
  [ 80  81  82  83  84]
  [ 85  86  87  88  89]
  [ 90  91  92  93  94]
  [ 95  96  97  98  99]]

 [[100 101 102 103 104]
  [105 106 107 108 109]
  [110 111 112 113 114]
  [115 116 117 118 119]
  [120 121 122 123 124]]]


In [21]:
# geeting max and min value with their indexs

arr = np.random.randint(0, 100, 50)

# get max value
print(arr.max())

# get max value index
print(f"index : {arr.argmax()}")

# get min value
print(arr.min())

# get min value index
print(f"index :{arr.argmin()}")

99
index : 3
0
index :17


# Array indexing

In [22]:
arr = np.random.randint(1,100, 10)

# print index 1
print(arr[1])

# print data from 0th index to 5th index
print(arr[0:6])

# or

print(arr[:5])

# print values from 2 to last index
print(arr[2:])


23
[28 23 55 95 18 78]
[28 23 55 95 18]
[55 95 18 78 90 92 77 32]


In [23]:
# change the values of index 1 to 4 to 100

arr[1:5] = 100
print(arr)

[ 28 100 100 100 100  78  90  92  77  32]


In [40]:
# copy of array
arr = np.arange(0,10,1)
print(arr)

# slicing does not copy but point to same data of original array hence any change in copy will be refelected into original array
cp_arr = arr.copy()
print(cp_arr)

cp_arr[:] = 100
print(arr)
print(cp_arr)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[100 100 100 100 100 100 100 100 100 100]


In [44]:
# accessing elements of 2d array

arr = np.random.randint(1,10,9)
D2_arr = arr.reshape(3,3)
print(D2_arr)
print(D2_arr[1][1])
# or
print(D2_arr[1,1])

[[7 6 5]
 [9 5 5]
 [1 9 1]]
5
5


In [45]:
# get subsection of matrix with slice notation
# get row 0 - 1 and get column 1 - 2
sub = D2_arr[:2,1:]
print(sub)

[[6 5]
 [5 5]]


In [49]:
# getting the data which satisfies the condition
arr = np.arange(1, 10,1)
print(arr)

# 1. get boolean array by applying condition
b_arr = arr > 5
print(b_arr)

# 2. get data from indexes where boolean true exist
print(arr[b_arr])

# Everything in one line
print(arr[arr>5])

[1 2 3 4 5 6 7 8 9]
[False False False False False  True  True  True  True]
[6 7 8 9]
[6 7 8 9]
